-- MySQL Script generated by MySQL Workbench
-- Fri May 22 20:57:34 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema 2017011301
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema 2017011301
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `2017011301` DEFAULT CHARACTER SET utf8 ;
USE `2017011301` ;

-- -----------------------------------------------------
-- Table `2017011301`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017011301`.`users` (
  `用户` VARCHAR(10) NOT NULL,
  `密码` CHAR(32) NULL,
  `创建时间` DATETIME NULL,
  `权限` VARCHAR(5) NULL,
  `状态` VARCHAR(5) NULL,
  PRIMARY KEY (`用户`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2017011301`.`selling`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017011301`.`selling` (
  `用户` VARCHAR(10) NOT NULL,
  `创建时间` DATETIME NOT NULL,
  `交易标题` VARCHAR(50) NULL,
  `交易内容` VARCHAR(1000) NULL,
  `交易状态` VARCHAR(5) NULL,
  PRIMARY KEY (`用户`, `创建时间`),
  CONSTRAINT `卖家`
    FOREIGN KEY (`用户`)
    REFERENCES `2017011301`.`users` (`用户`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `2017011301`.`buying`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `2017011301`.`buying` (
  `卖家` VARCHAR(10) NOT NULL,
  `创建时间` DATETIME NOT NULL,
  `买家` VARCHAR(10) NOT NULL,
  `申请时间` DATETIME NOT NULL,
  `申请备注` VARCHAR(50) NULL,
  `申请状态` VARCHAR(5) NULL,
  `购买评价` VARCHAR(50) NULL,
  PRIMARY KEY (`卖家`, `创建时间`, `买家`, `申请时间`),
  INDEX `买家_idx` (`买家` ASC) VISIBLE,
  CONSTRAINT `账单`
    FOREIGN KEY (`卖家` , `创建时间`)
    REFERENCES `2017011301`.`selling` (`用户` , `创建时间`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `买家`
    FOREIGN KEY (`买家`)
    REFERENCES `2017011301`.`users` (`用户`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
